spring:
  datasource:
    url: jdbc:mysql://${DBHOST}:${DBPORT}/${DB}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate #create